### ISSUE TITLE
Docker container can't read or write files

### ISSUE THREAD

**Issue by Vandaahl** [kopia/kopia#1877]
I made a docker-compose.yml file to try out the Kopia web ui and I'm getting errors whenever it either has to read or write files. For example, creating a new repository on the local filesystem generates the error: `Connect Error: INTERNAL: internal server error: connect error: unable to write blobcfg blob: PutBlob() failed for "kopia.blobcfg": unable to complete PutBlobInPath:/repo/kopia.blobcfg.f despite 10 retries: cannot create temporary file: open /repo/kopia.blobcfg.f.tmp.5cd15fa35cf5853a: permission denied`

My docker-compose.yml file:

```
version: '3.3'
services:
    server:
        ports:
            - '51515:51515'
        environment:
            - KOPIA_PASSWORD=test
        volumes:
            - '/home/user/me/docker/kopia/config:/app/config'
            - '/home/user/me/docker/kopia/cache:/app/cache'
            - '/home/user/me/docker/kopia/logs:/app/logs'
            - '/home/user/me/docker/kopia/repo:/repo'
        image: kopia/kopia
        command: server --address=http://0.0.0.0:51515 --insecure --ui --server-username=admin --server-password=admin
```
The user that runs the docker commands is also the owner of all directories configured in the docker-compose.yml file. Any suggestions?

Edit: I think I figured it out. I modified the config to have the container run as the correct user so permissions are now correct:

```
version: '3.3'
services:
    server:
        ports:
            - '51515:51515'
        environment:
            - KOPIA_PASSWORD=test
            - USER=1000
        user: '1000'
        volumes:
            - '/home/user/me/docker/kopia/config:/app/config'
            - '/home/user/me/docker/kopia/cache:/app/cache'
            - '/home/user/me/docker/kopia/logs:/app/logs'
            - '/home/user/me/docker/kopia/repo:/repo'
        image: kopia/kopia
        command: server --address=http://0.0.0.0:51515 --insecure --ui --server-username=admin --server-password=admin
```
