### ISSUE TITLE
Unable to understand that how to use Kopia with Docker

### ISSUE THREAD

**Issue by akash07k** [kopia/kopia#2045]
I'm very new to Kopia and trying to run Kopia on Docker.
The thing is that I want to backup my Docker volumes via Kopia and I don't want to use the CLI.
Instead of it, I want to use Web GUI.
The thing is that there's no proper documentation in Kopia's documentation regarding running it with Docker.
Only 1 simple command is provided which is not much helpful.
There's nothing on other sites too.
Now whenever I'm trying to take the snapshot of anything, I'm getting the errors such as "directory doesn't exist"
I'm unable to identify that what should I do and how?
Also, there should be a simple example so that users can easily identify the basics.
It is also not clear that can we use KopiaUI on linux servers if we don't use it via Docker?
If yes, then how? there's no information regarding that either.
If we can use KopiaUI/Web GUI even without installing it on docker, then please help with that.
Below is my docker-compose.yml:
```
version: "3"
services:
    kopia:
        image: kopia/kopia:latest
        container_name: "kopia"
        hostname: ${HOSTNAME}
        restart: unless-stopped
        ports:
            - ${HOST_PORT}:51515
        environment:
            - "KOPIA_PASSWORD=${KOPIA_PASSWORD}"
            - "TZ=Asia/Kolkata"
        volumes:
            - "./config:/app/config"
            - "./cache:/app/cache"
            - "./logs:/app/logs"
            - "/media/backup:/app/backup:ro"
        entrypoint: ["/app/kopia", "server", "--insecure", "--address=0.0.0.0:51515", "--override-username=${USERNAME}@${HOSTNAME}", "--server-username=${USERNAME}@${HOSTNAME}", "--server-password=${KOPIA_PASSWORD}"]

volumes:
    config:
    cache:
    logs:
    backup:

```
