### ISSUE TITLE
Kopia logs fails in Docker because of missing logs volume

### ISSUE THREAD

**Issue by marcosvrs** [kopia/kopia#2171]
logs failed to be saved/shown if I don't set the /app/logs folder as a volume.

Logs:
```
kopia              | Unable to create logs directory: mkdir /app/logs: permission denied
kopia              | Unable to create logs directory: mkdir /app/logs: permission denied
kopia              | 2022-07-10T00:02:46.828810+02:00  
kopia              | Server will allow connections from users whose accounts are stored in the repository.
kopia              | User accounts can be added using 'kopia server user add'.
kopia              | 
kopia              | 2022-07-10 00:02:46.828810666 +0200 CEST write error: unable to open log file: open /app/logs/cli-logs/kopia-20220709-220246-1-server-start.0.log: no such file or directory
kopia              | 2022-07-10 00:02:46.828985599 +0200 CEST write error: unable to open log file: open /app/logs/cli-logs/kopia-20220709-220246-1-server-start.1.log: no such file or directory
kopia              | SERVER ADDRESS: http://[::]:51515
kopia              | 2022-07-10T00:02:52.337773+02:00  Open the address above in a web browser to use the UI.
kopia              | 2022-07-10 00:02:52.337773856 +0200 CEST write error: unable to open log file: open /app/logs/cli-logs/kopia-20220709-220246-1-server-start.2.log: no such file or directory
kopia              | 2022-07-10T00:02:53.518977+02:00 WARN got invalid CSRF token for /api/v1/sources: e1abc9eee0da16ec601deb7136993d68c10ffe92fd18708dbef2dac61d3d5607, want e2c475287f2bb692c7ea61bbd9e89f18cc65f37eebf055096fbb8990367d193c, session c6c0144a-d41f-4b5d-bd38-d3396b042a6e
kopia              | 2022-07-10 00:02:53.518977215 +0200 CEST write error: unable to open log file: open /app/logs/cli-logs/kopia-20220709-220246-1-server-start.3.log: no such file or directory
kopia              | 2022-07-10T00:02:54.510670+02:00 WARN got invalid CSRF token for /api/v1/tasks-summary: e1abc9eee0da16ec601deb7136993d68c10ffe92fd18708dbef2dac61d3d5607, want e2c475287f2bb692c7ea61bbd9e89f18cc65f37eebf055096fbb8990367d193c, session c6c0144a-d41f-4b5d-bd38-d3396b042a6e
kopia              | 2022-07-10 00:02:54.510670894 +0200 CEST write error: unable to open log file: open /app/logs/cli-logs/kopia-20220709-220246-1-server-start.4.log: no such file or directory
kopia              | 2022-07-10T00:02:56.520566+02:00 WARN got invalid CSRF token for /api/v1/sources: e1abc9eee0da16ec601deb7136993d68c10ffe92fd18708dbef2dac61d3d5607, want e2c475287f2bb692c7ea61bbd9e89f18cc65f37eebf055096fbb8990367d193c, session c6c0144a-d41f-4b5d-bd38-d3396b042a6e
kopia              | 2022-07-10 00:02:56.520566734 +0200 CEST write error: unable to open log file: open /app/logs/cli-logs/kopia-20220709-220246-1-server-start.5.log: no such file or directory
kopia              | 2022-07-10T00:02:59.536591+02:00 WARN got invalid CSRF token for /api/v1/tasks-summary: e1abc9eee0da16ec601deb7136993d68c10ffe92fd18708dbef2dac61d3d5607, want e2c475287f2bb692c7ea61bbd9e89f18cc65f37eebf055096fbb8990367d193c, session c6c0144a-d41f-4b5d-bd38-d3396b042a6e
kopia              | 2022-07-10 00:02:59.536591484 +0200 CEST write error: unable to open log file: open /app/logs/cli-logs/kopia-20220709-220246-1-server-start.6.log: no such file or directory
kopia              | 2022-07-10T00:02:59.538993+02:00 WARN got invalid CSRF token for /api/v1/sources: e1abc9eee0da16ec601deb7136993d68c10ffe92fd18708dbef2dac61d3d5607, want e2c475287f2bb692c7ea61bbd9e89f18cc65f37eebf055096fbb8990367d193c, session c6c0144a-d41f-4b5d-bd38-d3396b042a6e
kopia              | 2022-07-10 00:02:59.538993716 +0200 CEST write error: unable to open log file: open /app/logs/cli-logs/kopia-20220709-220246-1-server-start.7.log: no such file or directory
kopia              | 2022-07-10T00:03:06.025350+02:00  upload triggered via API: 1000@c9b870159d85:/data/.docker/home-assistant/backups
kopia              | 2022-07-10 00:03:06.025350347 +0200 CEST write error: unable to open log file: open /app/logs/cli-logs/kopia-20220709-220246-1-server-start.8.log: no such file or directory
```

docker-compose:
```yaml
kopia:
    image: kopia/kopia
    container_name: kopia
    # ports:
    #   - 51515:51515
    user: "1000:998"
    command:
    - server
    - start
    - --insecure
    - --address=0.0.0.0:51515
    - --server-username=user
    - --server-password=secret
    volumes:
      - ./.docker/kopia/config:/app/config
      - ./.docker/kopia/cache:/app/cache
      - ./.docker/kopia/rclone:/app/rclone
      # - ./.docker/kopia/logs:/app/logs
      - ./:/data:ro
    environment:
      KOPIA_CHECK_FOR_UPDATES: "true"
      KOPIA_PASSWORD: secret
      TZ: Europe/Berlin
      USER: 1000
```
