### ISSUE TITLE
ERROR unable to initialize repository: unable to initialize repository: error opening repository: unable to open repository: invalid repository password

### ISSUE THREAD

**Issue by s-h-a-r-d** [kopia/kopia#2370]
I'm consistently get this error where first startup of kopia container works normally and I can setup B2 repo and syncing and everything else works fine, but the minute I restart the container I start getting this error in logs and container gets stuck in restart loop:

```
Server will allow connections from users whose accounts are stored in the repository.
User accounts can be added using 'kopia server user add'.
ERROR unable to initialize repository: unable to initialize repository: error opening repository: unable to open repository: invalid repository password
```
after that error, container restarts and gets the same error. And that loop continues indefinitely.
Happens with latest stable and unstable images.

Here is the docker-compose bit for kopia:
```
  kopia:
    image: kopia/kopia
    container_name: kopia
    user: "0"
    environment:
        KOPIA_PASSWORD: SuperSecretRepositoryPassword
        TZ: ${TZ}
    volumes:
        - ${DATADIR}/appdata/kopia/config:/app/config
        - ${DATADIR}/appdata/kopia/cache:/app/cache
        - ${DATADIR}/appdata/kopia/logs:/app/logs
        - ${DATADIR}/appdata/kopia/scripts:/app/scripts
        - ${NASDIR}/cloud:/app/backup:ro
    entrypoint: ["/app/kopia", "server", "--insecure", "--address=0.0.0.0:51515", "--override-username=kopia@localhost", "--server-username=kopia@localhost", "--server-password=SuperSecretPasswordForTheWebUI","--enable-actions"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kopia.entrypoints=websecure"
      - "traefik.http.routers.kopia.rule=Host(`kopia.${DOMAIN}`)"
      - "traefik.http.routers.kopia.tls=true"
      - "traefik.http.services.kopia.loadbalancer.server.port=51515"
    restart: always
```

**Comment by Chifilly** [comment]
I have the same issue too. Here's my compose file:
```yaml
services:
  kopia:
    container_name: kopia
    image: kopia/kopia:unstable # using unstable as I want to use bash scripts for actions
    command:
      - server
      - start
      - --ui
      - --insecure
      - --disable-csrf-token-checks
      - --address=0.0.0.0:51515
      - --server-username=${KOPIA_USERNAME}@${KOPIA_HOSTNAME}
      - --server-password=${KOPIA_PASSWORD}
      - --enable-actions
    user: "0:0"
    domainname: ${KOPIA_USERNAME}
    hostname: ${KOPIA_HOSTNAME}
    networks:
      main:
    ports:
      - "51515:51515"
    environment:
      TZ: Europe/London

      USER: ${KOPIA_USERNAME}
      KOPIA_PASSWORD: ${KOPIA_PASSWORD}
      KOPIA_PERSIST_CREDENTIALS_ON_CONNECT: true
    volumes:
      # ! Base mounts
      - ./volumes/kopia/config:/app/config
      - ./.tmp/kopia:/app/cache
      - ./volumes/kopia/logs:/app/logs

      # ! Extra mounts
      - ./scripts/pipes/kopia.pipe:/app/docker.pipe
      - ./extra/scripts/kopia:/app/scripts

      # ! Backup mounts
      - ./secrets:/app/backup/secrets:ro
      - ./volumes:/app/backup/volumes:ro
    restart: unless-stopped
```

Looking at `repository.config` it has all the correct information, and base64 decoding the contents of `repository.config.kopia-password` returns the correct password. There is also a `repository.config.mlock` which I don't know the purpose of but is empty

**Comment by s-h-a-r-d** [comment]
Ok same thing seems to be the issue for me as well. But in my defense the entering repository password in the WebUI is a bit unintuitive. This is how it looks: 

![image](https://user-images.githubusercontent.com/5573972/189178491-0f6a5c53-87ba-416a-b95c-aa1db563bdf3.png)

since you are asked to enter the password and then confirm it, that step makes it seem like you are creating a new password specifically for that repository. BUT in reality what it is asking for is the same password you supplied to `KOPIA_PASSWORD` in docker compose file. For some reason it just asks you to enter it twice.

I'm also not sure why the repository password is asked in the first place during the UI setup, as you have already provided it via environment variable.

**Comment by remus-selea** [comment]
> I have the same issue too. Here's my compose file:
> 
> ```yaml
> services:
>   kopia:
>     container_name: kopia
>     image: kopia/kopia:unstable # using unstable as I want to use bash scripts for actions
>     command:
>       - server
>       - start
>       - --ui
>       - --insecure
>       - --disable-csrf-token-checks
>       - --address=0.0.0.0:51515
>       - --server-username=${KOPIA_USERNAME}@${KOPIA_HOSTNAME}
>       - --server-password=${KOPIA_PASSWORD}
>       - --enable-actions
>     user: "0:0"
>     domainname: ${KOPIA_USERNAME}
>     hostname: ${KOPIA_HOSTNAME}
>     networks:
>       main:
>     ports:
>       - "51515:51515"
>     environment:
>       TZ: Europe/London
> 
>       USER: ${KOPIA_USERNAME}
>       KOPIA_PASSWORD: ${KOPIA_PASSWORD}
>       KOPIA_PERSIST_CREDENTIALS_ON_CONNECT: true
>     volumes:
>       # ! Base mounts
>       - ./volumes/kopia/config:/app/config
>       - ./.tmp/kopia:/app/cache
>       - ./volumes/kopia/logs:/app/logs
> 
>       # ! Extra mounts
>       - ./scripts/pipes/kopia.pipe:/app/docker.pipe
>       - ./extra/scripts/kopia:/app/scripts
> 
>       # ! Backup mounts
>       - ./secrets:/app/backup/secrets:ro
>       - ./volumes:/app/backup/volumes:ro
>     restart: unless-stopped
> ```
> 
> Looking at `repository.config` it has all the correct information, and base64 decoding the contents of `repository.config.kopia-password` returns the correct password. There is also a `repository.config.mlock` which I don't know the purpose of but is empty
> 
> After looking properly at my compose file again after pasting it here, I realised I had the wrong password in the `KOPIA_PASSWORD` environment variable (I was using the server password password variable instead of the repository password one) so I don't actually have the issue anymore

Thanks, this was helpful in my setup.

```
version: '3.3'
services:
  kopia:
    image: 'kopia/kopia:latest'
    container_name: kopia
    hostname: '${KOPIA_HOSTNAME}'
    restart: unless-stopped
    user: '1000:1000'
    ports:
      - '51515:51515'
    command:
      - server
      - start
      - '--ui'
      - '--insecure'
      - '--disable-csrf-token-checks'
      - '--address=0.0.0.0:51515'
      - '--server-username=${KOPIA_USERNAME}@${KOPIA_HOSTNAME}'
      - '--server-password=${KOPIA_REPOSITORY_PASSWORD}'
    environment:
      - TZ=Europe/Bucharest
      - USER=${KOPIA_USERNAME}
      - 'KOPIA_PASSWORD=${KOPIA_USER_PASSWORD}'
      - KOPIA_PERSIST_CREDENTIALS_ON_CONNECT=true
    volumes:
      # ! Base mounts
      - './config:/app/config'
      - './cache/dir:/app/cache'
      - './logs:/app/logs'
      # ! Backup mounts
      - '/mnt/host-data:/backuproot:ro'
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
```

I found it strange how the passwords are mapped.
In my case `KOPIA_PASSWORD` is actually the password of the user I have added to the repository to be able to connect to the server, which Is why I have it as `KOPIA_USER_PASSWORD`. 

Then the `--server-password` is actually the password I set for the repository when I have created it, but also of the Web UI.
Lastly, in my case the `USER` is the name of the user with UID:GID 1000:1000.

**Comment by ntolia** [comment]
I'm closing this one out as this was reported on Slack as having been addressed/answered. Please feel free to ping me or reopen if there is still an open question.

**Comment by louwers** [comment]
This is a UX bug. Since there are multiple repositories, why do we only need to supply one password?

**Comment by maxime1992** [comment]
Hello, I'm really struggling with all this. If anyone could help out that'd be much appreciated, it's driving me insane :upside_down_face:.

I've picked up the default docker compose file [here](https://kopia.io/docs/installation/#docker-images). 

When I start the container the first time, it's all good. If I boot it up for the first time, and restart it, it's all good.
But then, if I add a S3 repo and I can see on the UI I've got access to previous backups, without doing anything else, if I put down my docker compose and up it up straight after, I always end up with this error: 

```
ERROR unable to initialize repository: unable to initialize repository: error opening repository: get password: password prompt error: inappropriate ioctl for device
Enter password to open repository: 
Server will allow connections from users whose accounts are stored in the repository.
User accounts can be added using 'kopia server user add'.
```

I suspect I'm missing something with the `environment` for both `KOPIA_PASSWORD` and `USER`. What is this for?! I understand the `server-username` argument and the `server-password` which both seem to be for the web UI.

But the env variables `KOPIA_PASSWORD` and `USER`? I've got no clue :exploding_head:. Am I supposed to put the password I've used to encrypt my data before sending to S3? But then what about the user? The S3 user?

I'm tried so many configurations and nothing worked for me, it's a shame I'm quite desperate to switch to Kopia but this is really holding me back as I'm not able to make it work after a restart.

Any help would be much appreciated.

If that helps, my docker compose is like this:

```
version: '3.7'

services:
  kopia:
    image: kopia/kopia:latest
    hostname: my-hostname
    container_name: kopia
    restart: unless-stopped
    ports:
      - 51515:51515
    # Setup the server that provides the web gui
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=my-username
      - --server-password=ui-password
    environment:
      - KOPIA_PASSWORD=SOME_PASSWORD
      - USER=User
    volumes:
      # Mount local folders needed by kopia
      - ${PWD}/kopia/config/dir:/app/config
      - ${PWD}/kopia/cache/dir:/app/cache
      - ${PWD}/kopia/logs/dir:/app/logs
      # Mount local folders to snapshot
      - ${PWD}/kopia-files:/data:ro
      # Mount repository location
      - ${PWD}/kopia/repository/dir:/repository
      # Mount path for browsing mounted snaphots
      - ${PWD}/kopia/tmp/dir:/tmp:shared
```

Then:
- `docker compose up -d`
- connect to S3 backend (can use local Minio for example)
- `docker compose down`
- `docker compose up -d`
- `docker compose logs kopia` --> you'll see errors in the logs :shrug:
