### ISSUE TITLE
Restore process in docker ?

### ISSUE THREAD

**Issue by tiritibambix** [kopia/kopia#2530]
Hello.

I'm using Kopia in docker and I use
`- /srv/Files:/data:ro`
Where in `/srv/Files/` I got all the folders of all my apps.

What should I input in the `Destination` filed when restoring for example `/srv/Files/app1` ?

It restores in `/var/lib/docker/overlay2/564672c120cbd0df0238bee901cc56b96516dc5360719552b2e97e                                          ae8b165d45/diff/app/srv/Files/app1/` instead of `/srv/Files/app1`

Should I input `/data/app1` or `/srv/Files/app1`. Nothing works as I was expecting to.

If that helps, here's my docker-compose:
```
services:
  kopia:
      image: kopia/kopia:latest
      container_name: Kopia
      user: "0:0"
      restart: "unless-stopped"
      privileged: true
      cap_add:
        - SYS_ADMIN
      security_opt:
        - apparmor:unconfined
      devices:
        - /dev/fuse:/dev/fuse:rwm
      command:
        - server
        - start
        - --insecure
        - --htpasswd-file=/app/htpasswd/.htpasswd 
        - --address=0.0.0.0:51515
        - --server-username=myuser
        - --server-password=mypassword
      ports:
        - 51515:51515
      volumes:
        - /srv/Files/Kopia/shared:/tmp:shared
        - /srv/Files/Kopia/config:/app/config
        - /srv/Files/Kopia/cache:/app/cache
        - /srv/Files/Kopia/logs:/app/logs
        - /srv/Files/Kopia/htpasswd:/app/htpasswd
        - /srv/Files:/data:ro
      environment:
        USER: myuser
        KOPIA_PASSWORD: mypassword
        TZ: Europe/Paris
```
