### ISSUE TITLE
Docker: exec: "/app/kopia": stat /app/kopia: no such file or directory: unknown

### ISSUE THREAD

**Issue by AlexZorzi** [kopia/kopia#2551]
```
version: "3"
services:
  kopia:
    image: kopia/kopia:20220601.0.221817
    container_name: "kopia"
    hostname: thinkcentre
    restart: unless-stopped
    ports:
        - 51515:51515
    environment:
        - "KOPIA_PASSWORD=password"
        - "TZ=Europe/Rome"
    volumes:
        - "/home/user/kopia/config:/app/config"
        - "/home/user/kopia/cache:/app/cache"
        - "/home/user/kopia/logs:/app/logs"
    entrypoint: ["/app/kopia", "server", "--insecure", "--address=0.0.0.0:51515", "--override-username=admin@host", "--server-username=admin@host", "--server-password=password"]

```
if i run the above docker-compose.yml everything is fine, but if i switch to the latest version as of 06 november 2022 i get the following error 
`Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/app/kopia": stat /app/kopia: no such file or directory: unknown`
