### ISSUE TITLE
Not able to start server due to TLS not configured

### ISSUE THREAD

**Issue by droidus** [kopia/kopia#2672]
I am running this for the first time on a Ubuntu machine, and I get this error message when I attempt to start the server:
`ERROR TLS not configured. To start server without encryption pass --insecure`
I couldn't find anywhere in the guide how TLS is configured.  Can anyone please advise?  I would be using a self-signed cert.

**Comment by lupusA** [comment]
Hi, have a look at here: https://kopia.io/docs/repository-server/

The guide explains how to setup a kopia server using tls. 
If you are using docker, you may use my docker-compose:

```
version: '3.7'
services:
    kopia:
        user: ${UID}:${GID}
        image: kopia/kopia:latest
        hostname: hostname
        container_name: kopia-server
        restart: unless-stopped
        networks:
            - kopia
        ports:
            - 51515:51515
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        devices:
            - /dev/fuse:/dev/fuse:rwm
        command:
            - server
            - start
            - --disable-csrf-token-checks
            - --tls-cert-file=/certs/fullchain.pem
            - --tls-key-file=/certs/privkey.pem
            - --address=0.0.0.0:51515
            - --server-username=${SERVER_USR}
            - --server-password=${SERVER_PWD}
            - --server-control-username=${SERVER_CTRL_USER}
            - --server-control-password=${SERVER_CTRL_PWD}
        environment:
            KOPIA_PASSWORD: ${REPOSITORY_PWD}
            TZ: Europe/Berlin
        volumes:
            # Mount local folders needed by kopia
            - /volume1/docker/kopia-server/config:/app/config
            - /volume1/docker/kopia-server/cache:/app/cache
            - /volume1/docker/kopia-server/logs:/app/logs
            # Mount local folders to backup
            - /volume1/homes:/nas_homes:ro
            # Mount backup location
            - /volume1/backups/kopia-repo:/app/backup:shared
            # Mount paths for certificates
            - /usr/syno/etc/certificate/fullchain.pem:/certs/fullchain.pem:ro
            - /usr/syno/etc/certificate/privkey.pem:/certs/privkey.pem:ro
networks:
  kopia:
    name: kopia
```

Note that my certificates are mounted by docker under /certs. Kopia uses this path when setting up the server. The passwords are exported to an .env file. 

Cheers,
