### ISSUE TITLE
ERROR unable to create format manager: invalid repository password

### ISSUE THREAD

**Issue by eduardomarcos** [kopia/kopia#2679]
Hi kopia team.

First, thanks for this tool.

I found out that when I configure a repository in Azure Storage, and I set a password and a different user name other than root or the repository, the first time the docker container is up everything is ok. But, when the container restarts for whatever reason (update, management...), the Kopia container is not running properly and the logs says:

`ERROR unable to initialize repository: unable to initialize repository: error opening repository: unable to open repository: unable to create format manager: invalid repository password`

And I cannot even access the UI.

If I remove the repository settings from the docker volume and I start the container, it works...I just need to configure again the Azure repository settings with the password, etc and it works and I can see the previous created policies and snapshots. Again, if the container restarts...it breaks again with the same error.

I'm running the 0.12.1 version of Kopia in a Docker container with the following docker-compose:

kopia:
    image: kopia/kopia:latest
    container_name: kopia
    hostname: "kopia"
    user: "0:0"
    restart: "unless-stopped"
    privileged: true
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --address=0.0.0.0:51515
      - --server-username=XXX
      - --server-password=XXX
      - --insecure
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    volumes:
      - /mnt/kopia:/tmp:shared
      - "$CONTAINERS_PATH/kopia/config:/app/config"
      - "$CONTAINERS_PATH/kopia/cache:/app/cache"
      - "$CONTAINERS_PATH/kopia/logs:/app/logs"
      - /:/source
    environment:
      KOPIA_PASSWORD: XXX
      TZ: Europe/Madrid
      USER: XXX
    networks:
      net-data:
        ipv4_address: 172.10.3.8
    ports:
      - "8031:51515"

Any clue?

Thanks in advance

**Comment by bstaeheli** [comment]
It seems, that we have the same issue here. We get the same error message after a restart of the container

**Comment by sziyan** [comment]
I had the same issue and fixed it by adding `--password=REPO_Password` to docker compose command

**Comment by bstaeheli** [comment]
Thank you @sziyan 

I was confused with the passwords. It is important to setup the repo with the same password like `$KOPIA_REPO_PASSWORD` This works for me:

```
  kopia:
    image: kopia/kopia:latest
    container_name: kopia
    hostname: kopia
    restart: unless-stopped
    networks:
      - t2_proxy
    command:
      - server
      - start
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=root
      - --server-password=$KOPIA_USER_PASSWORD
    volumes:
      - $CONFIGDIR/kopia/config:/app/config
      - $CONFIGDIR/kopia/logs:/app/logs
      - /mnt/cache/tmp/kopia_cache:/app/cache
      - /:/data/hive_root:ro
      - /some/path:/data/backup-target
    environment:
      TZ: $TZ    
      USER: $PUID
      KOPIA_PASSWORD: $KOPIA_REPO_PASSWORD
      KOPIA_PERSIST_CREDENTIALS_ON_CONNECT: "true"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      # Traefik
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.kopia-rtr.entrypoints=https"
      - "traefik.http.routers.kopia-rtr.rule=Host(`kopia.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.kopia-rtr.middlewares=chain-authelia@file"
      # - "traefik.http.routers.kopia-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.kopia-rtr.service=kopia-svc"
      - "traefik.http.services.kopia-svc.loadbalancer.server.port=51515"
      ## Unraid
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/kopia/kopia/master/icons/kopia.svg"
      - "net.unraid.docker.webui=https://kopia.$DOMAINNAME"
```
