### ISSUE TITLE
UI: No information about initialization state?

### ISSUE THREAD

**Issue by IngwiePhoenix** [kopia/kopia#2769]
Hello!

I have set up a very basic reverse proxy with Caddy and pointed my Desktop instance at it - but the UI is just endlessly "initializing..." and the log doesn't tell me anything, except that it created and is sweeping a cache directory.

Technically, Caddy supports HTTP2 and thus gRPC proxying, and I can even see the initial connection too. Unfortunately, I have no response to if something is waiting or breaking in the logs of Kopia.

The setup:

The server is an ARMv8/aarch64 system, running Kopia compiled from source. The startup is handled via `dinit` and launched as such:

```
type = process
command = /sdcard/opt/kopia/dist/kopia_linux_arm64/kopia server start --address="http://192.168.2.1:51515" --file-log-level=info --log-level=warning --persist-credentials --ui --enable-actions --content-cache-size-mb=4096 --metadata-cache-size-mb=2048 --insecure
logfile = /var/log/kopia.dinit.log
depends-on = caddy
env-file = /sdcard/dinit.d/kopia.env
```
The env file:
```
KOPIA_CONFIG_PATH=/sdcard/etc/kopia/repository.config
KOPIA_SERVER_CONTROL_USER=<redacted>
KOPIA_SERVER_CONTROL_PASSWORD=<redacted>
KOPIA_SERVER_USERNAME=<redacted>
KOPIA_SERVER_PASSWORD=<redacted>
KOPIA_LOG_DIR=/var/log/kopia
KOPIA_CHECK_FOR_UPDATES=1
```

The Caddyfile entry:
```
backup.birb.it {
  reverse_proxy * 192.168.2.1:51515
}
```

(SSL/TLS is configured and confirmed working as I can access the GUI through my browser perfectly fine.)

On my Windows client, I used `https://backup.birb.it:443` as the repository URL. My local DNS server resolves this properly on the local network.

Once I entered my login details, all I see is:

```
16:06:18.328 Creating cache directory 'C:\Users\Ingwie Phoenix\AppData\Local\kopia\bcba4a36c4bc45d9' with max size 5242880000
--
16:06:18.487 establishing new GRPC streaming session (purpose=)
16:07:18.488 finished sweeping {"cache":"cache-storage","duration":"0s","totalRetainedSize":0,"tooRecentBytes":0,"tooRecentCount":0,"maxSizeBytes":5242880000,"inUsePercent":0}
16:08:18.488 finished sweeping {"cache":"cache-storage","duration":"0s","totalRetainedSize":0,"tooRecentBytes":0,"tooRecentCount":0,"maxSizeBytes":5242880000,"inUsePercent":0}
16:09:18.489 finished sweeping {"cache":"cache-storage","duration":"0s","totalRetainedSize":0,"tooRecentBytes":0,"tooRecentCount":0,"maxSizeBytes":5242880000,"inUsePercent":0}
16:10:18.490 finished sweeping {"cache":"cache-storage","duration":"31.8µs","totalRetainedSize":0,"tooRecentBytes":0,"tooRecentCount":0,"maxSizeBytes":5242880000,"inUsePercent":0}
16:11:18.492 finished sweeping {"cache":"cache-storage","duration":"0s","totalRetainedSize":0,"tooRecentBytes":0,"tooRecentCount":0,"maxSizeBytes":5242880000,"inUsePercent":0}
... it repeats ...
```

On the server:
```
# cat /var/log/kopia/cli-logs/latest.log
2023-02-17T12:30:52.100082Z INFO kopia/cli
Server will allow connections from users whose accounts are stored in the repository.
User accounts can be added using 'kopia server user add'.

2023-02-17T12:30:54.119800Z INFO kopia/cli Open the address above in a web browser to use the UI.
```

So I suppose something is not working - but neither server nor client are giving me any indication, waiting indefinitively. It'd be great to have a way to dig a little deeper to tell what's up.

Thanks and kind regards,
Ingwie

**Comment by SelfHostedJawn** [comment]
Were you able to get this working? I'm running into the same issue.

**Comment by IngwiePhoenix** [comment]
Nope. Gave up on Kopia and am back to square one...

**Comment by lupusA** [comment]
Hi @IngwiePhoenix, 

are you running a kopia behind a proxy? My guess is that choosing "Repository Server" and then entering the URL won't work with flag "--insecure". You have to setup kopia using tls and providing the certs to kopia. 

The proxy just have to forward the request as the backend already handles tls. 

Cheers,

**Comment by SelfHostedJawn** [comment]
@lupusA Do you know how short duration certs from letsencrypt should be handled for Kopia? I use caddy for my reverse proxy and the certs only last 90 days. Can I point Kopia to the .CRT and .KEY files that caddy downloads and manages? Would I need to restart Kopia every time the certs are updated?

**Comment by lupusA** [comment]
Hey @SelfHostedJawn, 

you can point to your pem and key files. Please take a look at my docker-compose. I am mounting my certs and then starting the server provding the path to the certs. 

```

version: '3.7'
services:
    kopia:
        user: ${UID}:${GID}
        image: kopia/kopia:latest
        hostname: diskstation
        container_name: kopia-server
        restart: unless-stopped
        networks:
            - kopia
        ports:
            - 8010:51515
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        devices:
            - /dev/fuse:/dev/fuse:rwm
        command:
            - server
            - start
            - --disable-csrf-token-checks
            - --enable-actions
            **- --tls-cert-file=/certs/fullchain.pem
            - --tls-key-file=/certs/privkey.pem**
            - --address=0.0.0.0:51515
            - --server-username=${SERVER_USR}
            - --server-password=${SERVER_PWD}
            - --server-control-username=${SERVER_CTRL_USER}
            - --server-control-password=${SERVER_CTRL_PWD}
        environment:
            KOPIA_PASSWORD: ${REPOSITORY_PWD}
            TZ: Europe/Berlin
            USER: "nas"
        volumes:
            # Mount local folders needed by kopia
            - /volume1/docker/kopia-server/config:/app/config
            - /volume1/docker/kopia-server/cache:/app/cache
            - /volume1/docker/kopia-server/logs:/app/logs
            # Mount local folders to backup
            - /volume1/homes:/nas_homes:ro
            # Mount backup location
            - /volume1/backups/kopia-repo:/app/backup:shared
            # Mount path for restoring snaphots
            - /volume1/backups/restore:/tmp:shared
            # Mount paths for certificates
            **- /usr/syno/etc/certificate/_archive/XiNQp0/fullchain.pem:/certs/fullchain.pem:ro
            - /usr/syno/etc/certificate/_archive/XiNQp0/privkey.pem:/certs/privkey.pem:ro**
networks:
  kopia:
    name: kopia
```
