### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by brianharwell** [kopia/kopia#2847]
I am trying to run Kopia using docker as documented here: https://kopia.io/docs/installation/#docker-images

Here is my compose file...
```
version: '3.7'
services:
    kopia:
        image: kopia/kopia:latest
        hostname: backupstation
        container_name: kopia
        restart: unless-stopped
        ports:
            - 51515:51515
        command:
            - server
            - start
            - --disable-csrf-token-checks
            - --insecure
            - --address=0.0.0.0:51515
            - --server-username="kopia"
            - --server-password="foobar"
        environment:
            KOPIA_PASSWORD: "foobar"
            USER: "brian"
            TZ: America/New_York
        volumes:
            - /opt/appdata/kopia/config:/app/config
            - /opt/appdata/kopia/cache:/app/cache
            - /opt/appdata/kopia/logs:/app/logs
            - /opt/appdata/kopia/repository:/repository
            - /mnt/volume1:/mnt/volume1
            - /mnt/volume2:/mnt/volume2
```

And when I try to login to the UI it prompts again for my credentials.

I have tried:
- kopia & foobar
- kopia@backupstation & foobar
- brian & foobar
- brian@backupstation & foobar

**Comment by lupusA** [comment]
Hi, try with "kopia" and "foobar" with quote signs. Than it should work. 
I will update the example. 

Cheers,

**Comment by brianharwell** [comment]
That worked thanks!

**Comment by GodsVictory** [comment]
I'm having the same issue:

```
version: '3.7'
services:
    kopia:
        image: kopia/kopia:latest
        hostname: server
        restart: unless-stopped
        ports:
            - 51516:51516
        environment:
            TZ: America/Chicago
            KOPIA_PASSWORD: 'kopia
        volumes:
            - ./config:/app/config
            - ./cache:/app/cache
            - ./logs:/app/logs
            - /data:/data:ro
        command:
            - server
            - start
            - --disable-csrf-token-checks
            - --insecure
            - --address=0.0.0.0:51516
            - --server-username="kopia"
            - --server-password="kopia"
            - --log-level=debug
```
