### ISSUE TITLE
[Discussion] Support for advanced sources

### ISSUE THREAD

**Issue by acul009** [kopia/kopia#2985]
### Introduction
Hello everyone,
I‘d be interested in a kopia which could be used for more than just files. After a short discussion on slack, I‘d like to ask everyone here for their opinions and ideas on how this issue could be tackled.

### The issue in general
After having looked at kopia, it seems like a wonderful backup solution. I‘d like to use it to backup my servers, but this also means having to handle database dumps and restores manually or via self written scripts.

My deployments are made using portainer on pure docker machines. I‘m not running a fancy docker swarm or even Kubernetes. While kubernetes has a few dedicated backup solutions, docker doesn‘t.

For managing databases, I could for example use borgmatic, but it only supports the backends that borg uses. My long term backups are saved in an S3 storage, which would mean another layer using rclone.

Frankly, I‘m sick of having to put in this much work to have a reliable backup every time I deploy a new application. Backups are important, they should‘nt be hard.

### How I imagine my use case could look

Before I go into detail on how this could work, I would like to introduce you to 3 other projects.

#### Traefik

Traefik is a reverse proxy. The incredible thing about Traefik is the support for different config sources. Traefik can read it‘s configuration from HTTP urls, from databases like Redis and most importantly, directly from docker container labels.

This means, that you don‘t have to maintain a seperate proxy configuration for each new deployed application, instead you can just add your routes right into your docker compose file. This makes deploying applications dead simple:
1) Have traefik running
2) deploy your prepared compose file

No extra digging trough another config or adding the routes through another gui. Your reverse proxy just becomes another part of your deployment.

#### Borgmatic

Borgmatic is a wrapper around borg. It directly supports dumping and backing up databases, just insert the address and credentials and Borgmatic will handle the rest for you. This makes it easy to backup databases, but failes at scale. If you have 20 applications, each with a directory to back up and a database too, you have to manually reconfigure your backup solution each time you deploy or take down an application.

#### camptocamp / bivac

This project is pretty close to what I‘d be looking for, but it seems unmaintained and I‘ve not seen anyone use it.

Bivac Reads your docker container and volumes and will automatically back them up using restic.

It uses short shells scripts from a configuration file to detect databases and can automatically dump them.

#### Back to kopia

What I would like to have then is this:

I want to add labels to either my containers or volumes and have kopia read those labels through the docker socket.

Dumps could be created from running the corresponding command inside a DB container and reading the output.

When restoring, the same functionality could be used to directly restore to the databse.

Databases could be detected using either the image or by checking for directories or files. (Like bivac does)
Alternatively you could just use the docker labels to tell kopia what to do.

This would make backups for docker containers effortless. You could deploy a new application, with the backup configuration inside the compose file and instantly have a running backup.

Restoring would be as easy as logging into the web-ui and hitting the restore button there.

While this might seem quite niche, I think a solution offering this, would take over docker the selfhosting community by storm.

### How this could be implemented

As my use case is specific to docker, it probably wouldn‘t make sense to directly implement it.

I would rather suggest a kind of plugin system, which would mean kopia could be expanded for more than just docker.

I could see this being used for things like Proxmox or on a central backup box, handling multiple NFS shares.

And this is where I need feedback.

I think starting with basic support for mySQL, mariaDB and PostgreSQL would make the most sense.

This would require the source plugin to define a few options like host, port and credentials.

The source could then implement 2 functions:
backup and restore, which would read from the specific configuration, perform the dump and return that data to kopia, which would handle the actual backup process.

### Why don‘t I just build my own fork or helper program?

While I could do that, I‘d much rather see a solution with more thought put into it than my usual projects. I‘m happy to help, but I‘m still missing quite a bit of experience.

Having first party support for something like this would make it interesting to far more people than a janky solution my a mediocre programmer like me.

**Comment by jkowalski** [comment]
What would the user experience be when taking snapshots? Can you propose a syntax for how exactly the labels would be discovered and used? This could be either CLI command flags or policies.

**Comment by acul009** [comment]
### Disclaimer (again :P )

This would probably involve quite a bit of work, but I think this could benefit a lot of people.
Especially people new to self-hosting (https://reddit.com/r/selfhosted) or admins new to using docker or databases might find this useful.
I don't want to seem like I'm demanding anything, I just want to get my thoughts out there, in the hopes that others find them useful or might improve on them.

### Concept for a Nextcloud Backup
```yaml
version: '3.6'

volumes:
  db:
  nextcloud:

networks:
  db:

services:
  app:
    image: nextcloud:26-apache
    restart: always
    command: apache2-foreground
    volumes:
      - nextcloud:/var/www/html:z
    networks:
      - db
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_DB: nextcloud
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      REDIS_HOST: redis
      VIRTUAL_HOST: ${NEXTCLOUD_HOST}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_HOST}
      NC_overwriteprotocol: https
      TRUSTED_PROXIES: "172.20.0.2 172.21.0.30"
      PHP_UPLOAD_LIMIT: ${UPLOAD_LIMIT}
    depends_on:
      - db
      - redis
    labels:
      # enable kopia for this container
      kopia.enable: true
      
      # groups are treated as one target to backup/restore
      # this means, that all containers in the same group will be restored and backed up at the same time
      kopia.group: nextcloud
      
      # Which folders should be backed up
      # kopia.folder.<folder name>
      kopia.folder.nextcloud_files: /var/www/html/data
      kopia.folder.nextcloud_themes: /var/www/html/themes
      
      # actions to be executed before starting the backup
      # kopia.<trigger>.<action name>.cmd: echo "this is the command to be executed in the container"
      # kopia.<trigger>.<action name>.user: this is the optional user which should execute the command
      kopia.before_backup.maintenance_on.cmd: "/var/www/html/occ maintenance:mode --on"
      kopia.before_backup.maintenance_on.user: 82:82
      
      # actions to be executed after finishing the backup
      kopia.after_backup.maintenance_off.cmd: "/var/www/html/occ maintenance:mode --off"
      kopia.after_backup.maintenance_off.user: 82:82
      
      # actions to be executed before starting the restore
      kopia.before_restore.maintenance_on.cmd: "/var/www/html/occ maintenance:mode --on"
      kopia.before_restore.maintenance_on.user: 82:82
      
      # actions to be executed after finishing the restore
      kopia.after_restore.set_permissions.cmd: "chown http:http /var/www/html"
      kopia.after_restore.set_permissions.user: 0:0
      kopia.after_restore.maintenance_off.cmd: "/var/www/html/occ maintenance:mode --off"
      kopia.after_restore.maintenance_off.user: 82:82
      kopia.after_restore.maintenance_fingerprint.cmd: "/var/www/html/occ maintenance:data-fingerprint"
      kopia.after_restore.maintenance_fingerprint.user: 82:82
      

  db:
    image: postgres:alpine
    restart: always
    networks:
    - db
    volumes:
      - db:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_DB: nextcloud
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    labels:
      # enable kopia for this container
      kopia.enable: true
      
      # groups are treated as one target to backup/restore
      # this means, that all containers in the same group will be restored and backed up at the same time
      kopia.group: nextcloud
      
      # Databases can't be backed up using folder, instead we can use command to generate a backup and feed it back
      # kopia.command.<command name>.backup: the output of this command will be backed up
      # kopia.command.<command name>.restore: the backup will be routed to stdin of this command
      # docker compose requires a double $ to actually write one
      kopia.command.db_dump.backup: pg_dumpall --clean -U $$POSTGRES_USER
      kopia.command.db_dump.restore: psql -U $$POSTGRES_USER
      
      
      # actions to be executed before starting the restore
      # Drop the current database before restoring the old one
      kopia.before_restore.drop_db.cmd: psql -U $$POSTGRES_USER DROP DATABASE $$POSTGRES_DB
```

After the root name "kopia" you would have the basic categories:

Control:
* enable
* group

Backup:
* folder
* command

Actions:
* before_backup
* after_backup
* before_restore
* after_restore

All actions and backups would have a name chosen by the user.
After the name the corresponding option would be selected (e.g. the path for a folder backup)
The value would be the actual value of the option.

### simpler implementation

If you'd like to keep the complexity of this expansion lower, you could also keep it down to these options:

kopia.enable: true
kopia.group: nextcloud
kopia.folder: /var/www/html/data
kopia.before_restore: psql -U $$POSTGRES_USER DROP DATABASE $$POSTGRES_DB
kopia.after_restore:
kopia.before_backup:
kopia.after_backup:



### Modular base system
If possible, this should be created on top of a modular system (a simple interface would probably suffice)

I can think of a few more adapters which could be interesting:

* Proxmox-Backup
* Hyper-V backup
* LXC Backups
* Backup a git repository
* Backup disk images

How exactly this modular base system could look is something I could take a crack at, but you're probably more suited for that than me. I'm happy to help or make personal suggestions if wanted.
