### ISSUE TITLE
Panic error during `kopia maintenance run --full` with rclone

### ISSUE THREAD

**Issue by marcosvrs** [kopia/kopia#3050]
I encountered a panic error when running the `kopia maintenance run --full` command using Docker and rclone as the backend storage. Here is the full output of the command:
```
$ sudo docker compose run kopia maintenance run --full
Running full maintenance...
Looking for active contents...
Looking for unreferenced contents...
GC found 52141 unused contents (36.1 GB)
GC found 8219 unused contents that are too recent to delete (1 GB)
GC found 3909 in-use contents (1.7 GB)
GC found 32892 in-use system-contents (53 MB)
Rewriting contents from short packs...
unable to rewrite content "me98d02cb7f79f09f99850b8db96fa6fd": unable to get content data and info: invalid checksum at qf532953b16192b04dfc2816ebb850dd2-s83f9c5a270ae873a113 offset 32 length 572/572: decrypt: unable to decrypt content: cipher: message authentication failed
unable to rewrite content "mafc7cd13de80d4796d7a406fb8d30644": unable to get content data and info: invalid checksum at q118975e206d21a8fe13482894a548890-sf448d1e3239193f1113 offset 32 length 570/570: decrypt: unable to decrypt content: cipher: message authentication failed
unable to rewrite content "m14fd61cbc901ee4f89f7036e8f4a381d": unable to get content data and info: invalid checksum at q2eea0c6e23f0f1b427295f9a8d8d7339-s8ada4de906750540113 offset 32 length 566/566: decrypt: unable to decrypt content: cipher: message authentication failed
panic: runtime error: slice bounds out of range [:1] with length 0

goroutine 4415 [running]:
github.com/kopia/kopia/repo/maintenance.findContentInShortPacks.func1({{0x0, 0x0}, 0x5, 0x0, {0xc00610bb80, 0x5, 0x8}})
        /home/runner/work/kopia/kopia/repo/maintenance/content_rewrite.go:205 +0x325
github.com/kopia/kopia/repo/content.(*WriteManager).IteratePacks(0x1?, {0x1cea8c8, 0xc0079806f0}, {0x1, 0x1, {0x0, 0x0, 0x0}}, 0xc00360ee70)
        /home/runner/work/kopia/kopia/repo/content/content_manager_iterate.go:222 +0x291
github.com/kopia/kopia/repo/maintenance.findContentInShortPacks({0x1cea8c8, 0xc0079806f0}, {0x1cfd020, 0xc0002c0dc0}, 0xc0007ebb60, 0xc00000, 0xd18c2e28000?)
        /home/runner/work/kopia/kopia/repo/maintenance/content_rewrite.go:193 +0x1be
github.com/kopia/kopia/repo/maintenance.getContentToRewrite.func1()
        /home/runner/work/kopia/kopia/repo/maintenance/content_rewrite.go:142 +0x1d2
created by github.com/kopia/kopia/repo/maintenance.getContentToRewrite
        /home/runner/work/kopia/kopia/repo/maintenance/content_rewrite.go:131 +0xf8
```

I am using Kopia version 0.13.0:
```
0.13.0 build: 7f69502bddd6650e7cb7a132291bc54920e58988 from: kopia/kopia
```

The Docker configuration for Kopia is as follows:
```yaml
kopia:
    image: kopia/kopia
    command:
      - server
      - start
      - "--address=0.0.0.0:51515"
      - "--insecure"
      - "--server-password=[redacted]"
      - "--server-username=[redacted]"
    environment:
      KOPIA_CHECK_FOR_UPDATES: "true"
      KOPIA_PASSWORD: [redacted]
    volumes:
      - ./.docker/kopia/cache:/app/cache
      - ./.docker/kopia/config:/app/config
      - ./.docker/kopia/rclone:/app/rclone
      - ./:/data:ro
    restart: unless-stopped
```

My backend storage is Mega, configured via rclone:
```
[mega]
type = mega
user = [redacted]
pass = [redacted]
```

And my repository.config:
```json
{
  "storage": {
    "type": "rclone",
    "config": {
      "remotePath": "mega:/backups/ironman",
      "atomicWrites": false,
      "dirShards": null
    }
  },
  "caching": {
    "cacheDirectory": "../cache",
    "maxCacheSize": 5242880000,
    "maxMetadataCacheSize": 5242880000,
    "maxListCacheDuration": 30
  },
  "hostname": "[redacted]",
  "username": "1000",
  "description": "My Repository",
  "enableActions": false,
  "formatBlobCacheDuration": 900000000000
}
```

When I run the `kopia snapshot verify --verify-files-percent=100` command, it completes:
```
$ sudo docker compose run kopia snapshot verify --verify-files-percent=100
Listing blobs...
  10000 blobs...
  20000 blobs...
  30000 blobs...
Listed 36340 blobs.
Processed 0 objects.
```

Currently, I'm running `kopia content verify --download-percent=100 --full --include-deleted`, but it is estimated to take over 200 hours to complete.
