### ISSUE TITLE
Cannot connect to kopia running on server from windows desktop

### ISSUE THREAD

**Issue by mjessa12** [kopia/kopia#3052]
i have my kopia instance running in docker and can access it from 192.168.1.24:51515, however, when trying to connect to it via the kopia desktop app its giving me the following error:

(i have created the user 'maysam' in the kopia console panel in docker)

![image](https://github.com/kopia/kopia/assets/72001246/84d3ab5c-5da9-4be5-83f3-fbbe5cc1e207)

any help to get this setup? thanks!!

**Comment by lupusA** [comment]
Hi @mjessa12, 

you probably entered the address in the wrong field. If you are using a repository server, webdav, or sftp you have to enter your address here:

<img width="743" alt="image" src="https://github.com/kopia/kopia/assets/37236531/269de401-4052-4ed3-bfc1-8538fb8136a3">

The hostname is the name of your machine or what you specify. It is used in combination with the username. 
If you setup a repository server, you have to add the user beforehand. 

Cheers,

**Comment by lupusA** [comment]
Hi @mjessa12, 

is your issue solved?

Cheers,

**Comment by mjessa12** [comment]
Hello

No, I am still not able to connect....

**Comment by mjessa12** [comment]
On the windows side, which server address do I enter into Kopia? 
1. My static ip 
2. My docker ip address
![image](https://github.com/kopia/kopia/assets/72001246/ab4e9a71-26b2-47aa-af95-59b6531b1f36)

4. Hostname in the stack?
![image](https://github.com/kopia/kopia/assets/72001246/ec9c9336-acec-4d85-a650-a095ed7b3bcc)

**Comment by mjessa12** [comment]
@lupusA

**Comment by lupusA** [comment]
Hi @mjessa12

so I assume you want to run a kopia repository server on docker and want your windows client to connect to it?

Cheers,

**Comment by mjessa12** [comment]
Yes exactly!! @lupusA

**Comment by lupusA** [comment]
Then we need to tweak your docker config. The flag _--insecure_ does not work with repository servers. This is my docker-compose file:

```
version: '3.7'
services:
    kopia:
        user: ${UID}:${GID}
        image: kopia/kopia:latest
        hostname: diskstation
        container_name: kopia-server
        restart: unless-stopped
        networks:
            - kopia
        ports:
            - 8010:51515
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        devices:
            - /dev/fuse:/dev/fuse:rwm
        command:
            - server
            - start
            - --disable-csrf-token-checks
            - --enable-actions
            - --tls-cert-file=/certs/fullchain.pem
            - --tls-key-file=/certs/privkey.pem
            - --address=0.0.0.0:51515
            - --server-username=${SERVER_USR}
            - --server-password=${SERVER_PWD}
            - --server-control-username=${SERVER_CTRL_USER}
            - --server-control-password=${SERVER_CTRL_PWD}
        environment:
            KOPIA_PASSWORD: ${REPOSITORY_PWD}
            TZ: Europe/Berlin
            USER: "nas"
        volumes:
            # Mount local folders needed by kopia
            - /volume1/docker/kopia-server/config:/app/config
            - /volume1/docker/kopia-server/cache:/app/cache
            - /volume1/docker/kopia-server/logs:/app/logs
            # Mount local folders to backup
            - /volume1/docker:/nas_docker:ro
            - /volume1/media:/nas_media:ro
            - /volume1/homes:/nas_homes:ro
            - /volume1/photo:/nas_photo:ro
            - /volume1/video:/nas_video:ro
            # Mount backup location
            - /volume1/backups/kopia-repo:/app/backup
            # Mount path for restoring snaphots
            - /volume1/backups/restore:/tmp
            # Mount paths for certificates
            - /usr/syno/etc/certificate/_archive/XiNQp0/fullchain.pem:/certs/fullchain.pem:ro
            - /usr/syno/etc/certificate/_archive/XiNQp0/privkey.pem:/certs/privkey.pem:ro
```
My docker-compose file just starts the server and mounts the volumes I want to backup on my nas (my NAS also creates snaphosts). If you only want a local folder on your windows machine to be snapshotted, you do not need additional volumes. Just make sure to provide folders for _/app/config_ _/app/cache/_ _/app/logs/_. 

You need a certificate or use a generated one for the repository server. My docker-compose mount exisiting certificates, which i point at when starting the server. You will find some additional instructions here: https://kopia.io/docs/repository-server/

After the server is running, you need to create a user for this repository server. As described in the documentation you can add them by running  ```docker exec -it kopia-docker kopia server user add myuser@mylaptop```

After the user has been added, open the Kopia UI on Windows. Select "Repository Server" and enter the address and port of your docker container. Make sure to provide "https". 

After that enter your SHA256 checksum of your certificate (see https://kopia.io/docs/repository-server/). Press next and then enter the user and the hostname (e.g. mylaptop). 

That shoud do it. 

Cheers,
