### ISSUE TITLE
Hostname changes when docker is updated

### ISSUE THREAD

**Issue by Snake883** [kopia/kopia#3414]
Upgrading Kopia docker container gives me a new docker container id, which gives me a new hostname, which is different than the repository hostname.

Which means I have to override the Kopia connection hostname everytime I want to connect to my **local repository**.

Which also means I need to keep track of the hostnames for each of my local repositories that I created with different versions of Kopia.

I'm also not sure if this is causing me other problems when trying to connect or do something with a repository via command line (I cannot connect to my repository via CLI).

![image](https://github.com/kopia/kopia/assets/8312560/90bf8ea1-24d2-4e35-b700-120612ab5625)

Notes:

- Docker container
- Unraid
- WebUI
- Local repositories

I'm not sure if this is a bug, or if Kopia docker container and the WebUI should be enhanced to accommodate.  I would like the WebUI to keep track of the repositories so I don't have to remember or save them separately from Kopia.  Because now I have multiple repositories, with multiple hostnames caused by docker updates, and Kopia is not keeping track, so I have to.  And I still can't do anything via CLI.

**Comment by lupusA** [comment]
Hi, 

if you are using a docker container, you can set the hostname in your docker-compose.yml or config file:
Here is mine:
```
version: '3.7'
services:
    kopia:
        user: ${UID}:${GID}
        image: kopia/kopia:latest
        hostname: diskstation
        container_name: kopia-server
        restart: unless-stopped
        privileged: true
        networks:
            - kopia
        ports:
            - 8010:51515
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        devices:
            - /dev/fuse:/dev/fuse:rwm
        command:
            - server
            - start
            - --disable-csrf-token-checks
            - --enable-actions
            - --tls-cert-file=/certs/fullchain.pem
            - --tls-key-file=/certs/privkey.pem
            - --address=0.0.0.0:51515
            - --server-username=${SERVER_USR}
            - --server-password=${SERVER_PWD}
            - --server-control-username=${SERVER_CTRL_USER}
            - --server-control-password=${SERVER_CTRL_PWD}
        environment:
            KOPIA_PASSWORD: ${REPOSITORY_PWD}
            TZ: Europe/Berlin
            USER: "nas"
        volumes:
            # Mount local folders needed by kopia
            - /volume1/docker/kopia-server/config:/app/config
            - /volume1/docker/kopia-server/cache:/app/cache
            - /volume1/docker/kopia-server/logs:/app/logs
            # Mount local folders to backup
            - /volume1/docker:/nas_docker:ro
            - /volume1/media:/nas_media:ro
            - /volume1/homes:/nas_homes:ro
            - /volume1/photo:/nas_photo:ro
            - /volume1/video:/nas_video:ro
            # Mount backup location
            - /volume1/backups/kopia-repo:/app/backup
            # Mount path for restoring snaphots
            - /volume1/backups/restore:/tmp
            # Mount paths for certificates
            - /usr/syno/etc/certificate/_archive/XiNQp0/fullchain.pem:/certs/ful                                                                                     lchain.pem:ro
            - /usr/syno/etc/certificate/_archive/XiNQp0/privkey.pem:/certs/privk                                                                                     ey.pem:ro
networks:
  kopia:
    name: kopia
```
Note the ```hostname: diskstation``` in the upper section of the config. You can then upgrade your docker container and the hostname remains the same. 

Please confirm, so I can close the issue :-)

Cheers,
