### ISSUE TITLE
//proc/1/map_files: operation not permitted

### ISSUE THREAD

**Issue by delightfuldude** [kopia/kopia#3444]
Hi!

I'm running kopiaui using the official [docker-compose](https://kopia.io/docs/installation/) on Debian 11:
```
version: '3.7'
services:
    kopia:
        image: kopia/kopia:latest
        hostname: kopia
        container_name: Kopia
#        user: "0:0"
        restart: unless-stopped
#        privileged: true
#        cap_add:
#            - SYS_ADMIN
#        security_opt:
#            - apparmor:unconfined
#        devices:
#            - /dev/fuse:/dev/fuse:rwm
        ports:
            - 51515:51515
        # Setup the server that provides the web gui
        command:
            - server
            - start
            - --disable-csrf-token-checks
            - --insecure
            - --address=0.0.0.0:51515
            - --server-username=USER
            - --server-password=PASSWORD
        environment:
            # Set repository password
            - KOPIA_PASSWORD="PASSWORD"
            - USER="USER"
            - TZ=Europe/Berlin
        volumes:
            # Mount local folders needed by kopia
            - ./config:/app/config
            - ./cache:/app/cache
            - ./logs:/app/logs
            # Mount local folders to snapshot
            - /opt/containers:/data:ro
            # Mount repository location
            - /home/admin/repo:/repository
            # Mount path for browsing mounted snaphots
            - ./tmp:/tmp:shared
        networks:
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.kopia.entrypoints=websecure"
            - "traefik.http.routers.kopia.rule=Host(`kopia.domain.com`)"
            - "traefik.http.routers.kopia.tls=true"
            - "traefik.http.routers.kopia.tls.certresolver=http_resolver"
            - "traefik.http.routers.kopia.service=kopia"
            - "traefik.http.services.kopia.loadbalancer.server.port=51515"
            - "traefik.docker.network=proxy"
            - "traefik.http.routers.kopia.middlewares=default@file"
networks:
    proxy:
        external: true
```

Everything is done in the webui. Creating the repository works, but when the snapshot is defined, kopia throws this error when pressing estimate:

```


08:44:08.008 error in proc/1/map_files: readdirent //proc/1/map_files: operation not permitted
--
08:44:08.009 error in proc/1: readdirent //proc/1/map_files: operation not permitted
08:44:08.009 error in proc: readdirent //proc/1/map_files: operation not permitted
08:44:08.009 error in .: readdirent //proc/1/map_files: operation not permitted
08:44:08.009 Included files 10 KB ...100 KB:       1 files, total size 38.4 KB
08:44:08.009 Included files 0 B   ...  1 KB:    3652 files, total size 0 B
08:44:08.009 Excluded files: None

```
