### ISSUE TITLE
Kopia doesn't snpashot if I'm not connected? 

### ISSUE THREAD

**Issue by DimitriDR** [kopia/kopia#3544]
Hi,

It's likely a problem from my side but there's no discussions specifically targeted on Kopia so I'm posting it here, maybe it's a real issue.

So, I configured my Kopia as server, I have the `root` user, managing two different path to backup (on different B2 buckets too). I configured it to snapshot each day at 5:00 AM.

![image](https://github.com/kopia/kopia/assets/56969769/dd9c3e29-3048-4920-8115-3aa5ed7899ac)

Both on global (`username: *`) _and_ `username: kopia`.

There's the thing, Kopia doesn't do that. I need to be connected for Kopia to start the snapshot.

![image](https://github.com/kopia/kopia/assets/56969769/41068dd9-1db2-44a1-87a6-fd97ca98cc0a)

It works two times, likely because I didn't log off. But it means, the other backup I have isn't backed up.

Is there a misconfiguration from me? Or a concept I didn't understood? 

EDIT: I also prefer using CLI, so if I can ditch the web UI in the solution, I don't mind. 

Thanks in advance! 😓

**Comment by lupusA** [comment]
Hi @DimitriDR, 

What is you setup exactly? Client - Repository Server - B2? 

Where are the paths located that need to be snapshotted? For me, I have setup a repository server on my nas where all my clients connect to.I am regularly syncing the repository to a another drive. The original repository lives in the nas itself.

If you setup a repository server or another instance, Kopia needs to connect to that server to create snapshots I guess. 

Cheers

**Comment by DimitriDR** [comment]
> What is you setup exactly? Client - Repository Server - B2?

You guess right!

Paths are on the same machine Kopia is. To be honest, it's two paths mounted with CIFS, the reals location is on my NAS.

Would the simplest and safest solution be simply to use Kopia as a client and not as a server? If so, would I have to be connected to my Kopia/B2 repository?

**Comment by lupusA** [comment]
I guess the simplest solution is to let kopia run on your nas. There you can snapshot your directories using for example a B2 repository. You can also use a filesystem repository (e.g. on the nas) and let that sync to a B2 repository regularly. 

By doing this you have a local backup for faster restores and a remote backup in case of a data loss scenario. You can sync regularly using the cli. Or use the B2 directly.

I am running the kopia repository server on my nas. It also serves as a client to create snapshots for it's mounts (photo, video etc). Also the windows clients on my network snapshot to the repository server. 

I am running kopia as a docker instance on my nas btw. 

Cheers

**Comment by DimitriDR** [comment]
I don't want to have Docker on my NAS, it's super slow, and that's not the main problem. Kopia can access to the mounted directories, and make snapshot but only when I logging on the web UI. I don't know it should have a routine or a cron job to make it, I don't understand anything anymore.

**Comment by lupusA** [comment]
Something is odd then, kopia can create snapshots even when you are not logged in. How do you start kopia on your nas?

**Comment by DimitriDR** [comment]
I tried to just use the CLI Kopia client and it didn't make a snapshot during the night despite having a schedule at 5 AM.

Let's not talk about the server, which as usual has done nothing until I connect to kopia.mydomain.com. 

The NAS is DS920+. But I don't see what difference it makes whether it runs on my NAS or not.

Maybe I didn't make myself clear, but I have a server that runs 24/7 **and** a NAS that runs 24/7. 

So whether Kopia runs on the NAS or the server, it'll be the same. Whether the source is directly from the NAS or the CIFS mount doesn't change the fact that Kopia (as server in a Docker container) doesn't make any scheduled backups. I'll post the kopia yalm I use because maybe I fucked up:

```
version: "3.9"

services:
  kopia:
    image: kopia/kopia:latest
    container_name: kopia
    restart: unless-stopped
    hostname: kopia
    networks:
      - kopia-network
    dns:
      - 192.168.80.1
    command:
      - "server"
      - "start"
      - "--insecure"
      - "--address=0.0.0.0:51515"
      - "--server-username=SecondMoon"
      - "--server-password=KOPIAPASSWORD"
    environment:
      KOPIA_PASSWORD: KOPIAPASSWORD
      USER: SecondMoon
    volumes:
      - "/mnt/docker/kopia/config:/app/config:rw"
      - "/mnt/docker/kopia/cache:/app/cache:rw"
      - "/mnt/docker/kopia/logs:/app/logs:rw"
      - "/mnt/docker/kopia/tmp:/tmp:shared"
      - "/mnt/saves/kopia:/repositories:rw"    # Local saves directory
      - "/mnt/docker:/tobebackup/docker:ro"    # Docker directories to save
      - "/mnt/photos:/tobebackup/photos:ro"    # Photos directories to save
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kopia.entrypoints=https"
      - "traefik.http.routers.kopia.rule=Host(`kopia.mydomain.com`)"
      - "traefik.http.routers.kopia.tls=true"
      - "traefik.http.services.kopia.loadbalancer.server.port=51515"
      - "traefik.docker.network=kopia-network"

networks:
  kopia-network:
    external: true
```

Then, when I connect to my B2 repo:

![image](https://github.com/kopia/kopia/assets/56969769/e007ef8e-4686-42f0-9385-75828d64ca76)

I have this UI.

Then, when I click on /tobebackup/photos

![image](https://github.com/kopia/kopia/assets/56969769/c6261cf3-0d33-4c58-861a-8bf3da90c2ac)

We can see Kopia just launched a snapshot after I connected myself. However, an auto snapshot is required every 5:00 (or 6:00 depending of the local hour because I think the Docker container is in UTC but it's just a detail that doesn't matter)

![image](https://github.com/kopia/kopia/assets/56969769/190dd939-60b6-4146-aab7-ac9e8e8596d7)
