### ISSUE TITLE
Kopia > Rclone > SFTP > Synology is not working

### ISSUE THREAD

**Issue by thierrybla** [kopia/kopia#4243]
Hi, I am trying to backup using kopia via rclone to my synology, I have confirmed that I can create files and see all folders when purely using the rclone command in the kopia container but once I try and create repository it keeps throwing the following error:
`Connect Error: INTERNAL: internal server error: connect error: unable to write blobcfg blob: PutBlob() failed for "kopia.blobcfg": unable to complete PutBlob(kopia.blobcfg) despite 10 retries: Write kopia.blobcfg.f-1827612010336891037: 405`

I have tried multiple rclone versions but none seem to work so far.
I also tried WEBDAV (without rclone) and similar things are happening when trying to connect to the synology.

Is there a problem with Synology and Kopia? is there a hidden setting I am missing?

Here is my rclone config:
```
[synology]
type = sftp
host = 192.168.1.73
user = user
pass = password
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum
```

And kopia container docker compose:

```
services:
  kopia-synology:
    image: kopia/kopia:latest
    hostname: kopia-synology
    container_name: kopia-synology
    restart: unless-stopped
    ports:
      - 51515:51515
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=user
      - --server-password=password
    environment:
      KOPIA_PASSWORD: "password"
      USER: "user"
    volumes:
      - /mnt/ssd-tank/docker-files/kopia-synology/config:/app/config
      - /mnt/ssd-tank/docker-files/kopia-synology/cache:/app/cache
      - /mnt/ssd-tank/docker-files/kopia-synology/logs:/app/logs
      - /mnt/ssd-tank/docker-files/kopia-synology/rclone:/app/rclone
      - /mnt/ssd-tank/docker-files:/data/docker-files:ro
      - /mnt/tank/personal-data:/data/personal-data:ro
```

If anyone has an idea on how to fix this, or needs more info, please let me know.
