### ISSUE TITLE
Confusion about server TLS when behind reverse proxy and trying to connect client

### ISSUE THREAD

**Issue by yatesco** [kopia/kopia#4382]
I have a reverse proxy exposed using tailscale which exposes my privately hosted kopia docker-compose:

<img width="848" alt="Image" src="https://github.com/user-attachments/assets/9ab3eebe-8890-4e5d-8bcd-50d8db213ca1" />

The Kopia server has a repository backed by a local FS and snapshots of another local directory are being backed up correctly. 

The Kopia server is defined using (modified from https://kopia.io/docs/installation/#docker-images):

```yaml
services:
  kopia:
    image: kopia/kopia:latest
    hostname: Hostname
    container_name: Kopia
    restart: unless-stopped
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=admin
      - --server-password=${KOPIA_SERVER_PASSWORD}
    environment:
      # Set repository password
      KOPIA_PASSWORD: ${KOPIA_PASSWORD}
      USER: "User"
    volumes:
      # Mount local folders needed by kopia
      - ${PWD}/config/kopia:/app/config
      - ./${VOLUME_LIVE}/kopia/logs:/app/logs
      - ./${VOLUME_LIVE}/kopia/cache:/app/cache
      # Mount local folders to snapshot
      - ./${VOLUME_BACKUP_STAGED}/:/data:ro
      # Mount repository location
      - ./${VOLUME_BACKUP_ENCRYPTED}/kopia:/repository
      # Mount path for browsing mounted snaphots
      - ${PWD}/kopia_snapshots:/tmp:shared
    labels:
      traefik.enable: true
      traefik.http.routers.kopia.rule: Host(`kopia.${DOMAIN}`)
      traefik.http.services.kopia.loadbalancer.server.port: 51515
```

This works such that https://kopia.my.domain on my client machine, which has no access to the docker directly shows:

<img width="1230" alt="Image" src="https://github.com/user-attachments/assets/73880eee-e269-4de9-ae50-341d2c717981" />

(NOTE: the certificate is generated by lets encrypt via trafiek's integration. The HTTPS certificate is *not* available to the kopia server process and the kopia server process is *not* started with any TLS directives.

I've added a username/password for the client, so on the kopia server:

```bash
root@Hostname:/app# kopia server users list
<ME>@<CLIENT-MACHINE>
```

On the client machine I'm trying to connect to the kopia server and it fails:

``` bash
❯ kopia repository connect server --url https://kopia.ts.colinyates.co.uk
Connecting to server 'https://kopia.my.domain' as '<ME>@<CLIENT-MACHINE>'...
Enter password to open repository: 

ERROR failed to open repository: unable to establish session for purpose=: error establishing session: Session(): failed to exit idle mode: dns resolver: missing port after port-separator colon
ERROR error connecting to API server: unable to establish session for purpose=: error establishing session: Session(): failed to exit idle mode: dns resolver: missing port after port-separator colon
```

The [instructors for connecting to the client](https://kopia.io/docs/repository-server/) state:

"kopia repository connect server --url https://<address>:51515 \
  --server-cert-fingerprint 48537cce585fed39fb26c639eb8ef38143592ba4b4e7677a84a31916398d40f7"

but I don't _have_ a certificate fingerprint defined for the server? 

Can somebody please clarify:
 - is the fact this is reverse proxied with a TLS from letsencrypt a red herring? I assume so.
 - how do I get the server fingerprint

Thanks!

**Comment by matthiasemde** [comment]
Hi @yatesco,

can you share a bit more about how you were able to get everything running in the end?

I am using a similar setup as you (you can check it out [here](https://github.com/matthiasemde/Pandora/blob/add-kopia/services/kopia/flake.nix)): kopia started with `--insecure` flag, traefik performing the TLS termination, and a tunnel (cloudflare in my case). The server and the web UI are running fine but when connecting using the windows CLI, I get error:
```
ERROR failed to open repository: unable to establish session for purpose=: error establishing session: unable to initialize session: rpc error: code = PermissionDenied desc = unexpected HTTP status code received from server: 403 (Forbidden); transport: received unexpected content-type "text/html": EOF

ERROR error connecting to API server: unable to establish session for purpose=: error establishing session: unable to initialize session: rpc error: code = PermissionDenied desc = unexpected HTTP status code received from server: 403 (Forbidden); transport: received unexpected content-type "text/html": EOF
```

Interestingly, if I enter wrong credentials on purpose, I get the same error - so I suspect traefik to be at fault here, messing up something.

The official docs mention something about an `grpc_pass` option on the reverse proxy, but I did not see any such option in your config.

Any help would be greatly appreciated!

Cheers
Matthias

**Comment by yatesco** [comment]
> Hi [@yatesco](https://github.com/yatesco),
> 
> <snip>
>
> Cheers Matthias

Hey - I ended up moving over to restic a while back and I can't really remember how I solved it. I do remember caddy (over traefik) being a revelation of simplicity though!

**Comment by matthiasemde** [comment]
Thanks for the reply. I'll do some more testing to see whether the problem is with the cloudflare tunnel, traefik or the kopia server. Once I have figured out a solution, I'll post it here :)

**Comment by mc2285** [comment]
Did you manage to figure that out @matthiasemde? The maintainer has asserted numerous times in other issues that Kopia requires to do TLS termination by itself for some imprecise internal reasons so I assume it is not supposed to work with a reverse proxy that terminates TLS which is a shame

**Comment by matthiasemde** [comment]
Hi @mc2285,
i also moved away from cloudflare and to a self-hosted reverse proxy, which allows me to do the TLS termination myself (which I prefer anyways). I haven't yet gotten back to setting up kopia, but I'm pretty confident that it will work.

So as a reverse-proxy I use [frp](https://github.com/fatedier/frp) on a cheap VPS (4€ per month). You can check out the vps configuration [here](https://github.com/matthiasemde/vps-config) and the client configuration [here](https://github.com/matthiasemde/Pandora/pull/13).

So far I am very happy with the simplicity and performance of frp - no uploud/dowload throttling, no max file size and full TLS coverage 👌 
Hope this helps :)
Best, Matthias

**Comment by Mossop** [comment]
I got this working with traefik. You have to have kopia configured with a TLS certificate (i.e. don't run with --insecure) then have traefik connect to it via https as described in [the gRPC guide](https://doc.traefik.io/traefik/user-guides/grpc/#with-https). I cheated and used insecureSkipVerify by creating a file configuration provider than looked like this:

```
http:
  serversTransports:
    insecure:
      insecureSkipVerify: true
```

Then in set the following labels in the docker compose file:

```
      - "traefik.http.services.kopia.loadbalancer.server.port=51515"
      - "traefik.http.services.kopia.loadbalancer.server.scheme=https"
      - "traefik.http.services.kopia.loadbalancer.serversTransport=insecure@file"
```
